travis:
  secure:
    BINSTAR_TOKEN: Fe+uEbqpsg0iFWYVsKFVb1m2y8QIAn1DgunbtJF6QY51i+01aYLkPNyzgCR+QdjSSDwXkYyGoQt3EGHdXJbXatCf5RcEMFijEnimBStYcFe1wUjlRmGSJ7NBoKMeC17Sf4RvFYyBd87LcOdISTupnnFzm/ItVQdustRyedwqXtEc2xFYxI3cm245kbseJVNsFAnMnpij6jwP8qeaVpX/HDlHZV5lYkhgWTouyeMxtRTncaOSvqGIxQ7jgfAAVSrheeXT5nY2R8Cmpm/hkLtpkE0mNLMhQThLYZ88kiwWEsb6qzhVDMLr4h8ySj+FrhAGhwbpaNp1Vtft0wym1ATP4beHrZRsLHgkgaQmSCYEB3pJWekB+rbftcryuCcayWOlt2NEGuJmntu98yY2Uf8gokrdtYtgkvxb6lSyEwBJ5+V1bGL+AQUzMdToguPg1InCVz+80tmvU7QxUrpumInmtU0vLm8tmgBpoeKQVd4i/cxWAa8+B6Ks3Z7tQhZF/PX0pUoeV7chK/IaqhIrS78HOvDVeNNBL6bnFTvilHQMB+w2yAc0+nKGKHsMCnehNC/QmEHjm0fdtQXeniaAnxtQmNgARPuXG6yOx1wC6jvjO2QC+f+4EkDXJH3zuyr//tb9Mugj9VjXz0qPjpHsSWWpEa/CAz1cccHOUaaPDa38IJI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
