travis:
  secure:
    BINSTAR_TOKEN: O9atZqJ6YocYtEZw+HmYMvEts164ivUBXAEFySe5ILa4xjTny84iZhcpwn4uycLBRBRczMXWkWrWgk1GmFDPZaJxKrdUT6Sfu78bfe3u+K6gUT8rhqYPoeBeZmA3NClM5xCajiXOUVYtWVWFoOXdTV9h6drYVd6S5D0n+C6hGrXo4Y4t8vQSsejLZXahyEKByEMgQu3v4y74bCFIFBSsa6xjbFBzSgSQa7cTHhMyvbwQDUj5G1yMWA6NXVE/qQVB0pJneQfcvKk4PU3zprSEVAmt6hIViITUw/9n2i6k3mASQkIKf6CyXZzBq025WiTyqvhUjmOpaw+Bt1qJvCCdZQcOCKM0Fl78Q3nJsXsKkzhgzC8T3ZBu5I4CEoll5sbumR1rKrvL22OGC75v8vRlylhV1SxhlinCrzbMdVJNnbJXIStY7rFgD+F+xNk9m4rjCys8ZDyz6KVCvH60BoH9YhfifFdQAYNsIahIaoHNVSI+plEOCREkMmmiC1+5ZfW952NKw/3WwcgIVKxjCttIyxu9bTnEHMzEn9FlkswoFYjkOsR8DujLVX9Z3qQVXsseJpeVJONXURwJCc4zW4D3F9sYP4v/ngoxBT6mAjy37MmFpgIxF2eh/qeEH6xLSz4lYE4n0ryGEY+ZYw/sK5+/GkaQ+WahNYfhOhT8ifL44eE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
